### ISSUE TITLE
気になったところ

### ISSUE THREAD

**Issue by masuP9** [lunaluna/wordcampogijima2018-slides#1]
## header に role="banner" は暗黙のARIAセマンティックと等価なのでいらないです

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L65

see also https://momdo.github.io/html-aria/#rules-wd

## footer は main > footer にしたいですね。やっぱり。

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L68-L71

## header 冗長な気がします

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L74

※あっても問題ではないです。

## 目次のマークアップ

`section[role="navigation"] > h2` ですかねー。 `header` と `nav` が冗長に見えます。

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L73-L78

あと `nav` に `role="navigation"` はいらないですー。

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L79

せっかくARIA 使うなら `ul[role="directory"]` としてもいいとおもいます。

## `strong` or `em`

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L149

強調の意なら `em` かなぁ。わりとこの後もありますね。

## `dl` だけで良いのでは

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L553-L555

これもこの後いくつかありますね。

## アクセシビリティ情報って？

独自用語っぽいので説明がいりそう。

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L589

## `aria-label` の説明

https://github.com/lunaluna/wordcampogijima2018-slides/blob/8da1c21ae14a14032544d1a14a58d6d17ab763a5/index.html#L610-L611

ラベル（名前）付けする属性、ぐらいで良さそう。またそれぞれの属性でこんなときに使いますっていうのがあったほうがわかりやすいかもですね。

**Comment by lunaluna** [comment]
> header に role="banner" は暗黙のARIAセマンティックと等価なのでいらないです

これ、カバー画像の仕様が変わって画像1枚になりました。この場合は `role="banner"` ありでいけますか？

```
			<section class="slidepage start-page01">
				<div role="banner">
					<h2 class="pagetitle"><img src="./img/cover.png" alt="明日からできる自作テーマ・受託プロジェクトのアクセシビリティ入門2018 セッションカバー画像"></h2>
				</div>
			</section>
```

**Comment by lunaluna** [comment]
> footer は main > footer にしたいですね。やっぱり。
> header 冗長な気がします

ここも結局各ページごと（ `section` ごと）に入ってるので、これも `div` にしちゃったほうがいいのかなぁ…？

**Comment by masuP9** [comment]
`<div role="banner">` は `<header>` と等価なので、`<header>` 使ったほうが良いかと。ただ、この場合、`header` は冗長かなと思います。

```html
<section class="slidepage start-page01">
  <h2 class="pagetitle"><img src="./img/cover.png" alt="明日からできる自作テーマ・受託プロジェクトのアクセシビリティ入門2018 セッションカバー画像"></h2>
</section>
```
